[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install --prefix client",
  "npm install --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "npm run build --prefix server"
]

[start]
cmd = "node server/dist/src/server.js"
